apiVersion: v1
kind: Pod
metadata:
 name: azure-disk-pod
spec:
 containers:
  - image: microsoft/sample-aks-helloworld
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
 volumes:
      - name: azure
        azureDisk:
          kind: Managed
          diskName: AzureDiskJioACS
          diskURI: /subscriptions/82d177b6-85d4-44d7-a2c1-68527f21139f/resourceGroups/jioacscluster1-rg_jio-acs-cluster1_centralindia/providers/Microsoft.Compute/disks/AzureDiskJioACS