apiVersion: v1
kind: Pod
metadata:
 name: azure-files-pod-1
spec:
 containers:
  - image: microsoft/sample-aks-helloworld
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
 volumes:
  - name: azure
    azureFile:
      secretName: azure-secret
      shareName: pvcfileshare
      readOnly: false